### ISSUE TITLE
Enhancement , Preset launch

### ISSUE THREAD

**Issue by Howlswolf** [bitfocus/companion-module-wled-websocket#1]
Just found out about WLED module !!! this is great, 

Ran some test yesterday at home with my setup, it seem to work as intended.  One thing that is missing is the ability to select/activate a presets . Hopefully you can add that with the info from the api.  I saw quickly that Playlist seem to be available...

**Comment by leonreucher** [comment]
Thank you for your feedback. I implemented the changes, should be available in the next beta.

**Comment by Howlswolf** [comment]
wow this is super quick , thanks a bunch !!!  I cant wait to test it out :)

**Comment by leonreucher** [comment]
You're welcome 🙂 
Just let me know if anything is missing or not working as expected 👍🏻
